### PR TITLE
fix alt-ctrl-del interpreted as delete

### PR DESCRIPTION
**Pull request by atamu**
I have accidentally deleted queues and topics by locking computers / bringing up the task manager with the application open.
(alt-ctrl-del and then enter)

This change will save my job. :)

I know you can use ctrl-l to lock a windows machine but - "old dogs can't learn new tricks" and this habit is hard for me to break.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 5.1.0-keycombo.24.build.827 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/38729817) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/caeb0267bd by @)

**Review by SeanFeldman — APPROVED** [review]

**Review by ErikMogensen — APPROVED** [review]

**Comment by ErikMogensen** [comment]
I hope that you get to keep your job 😃

**Comment by paolosalvatori** [comment]
I hope this doesn't cost you the job... but this is good example of why in production environment you should always use the Service Bus Premium with Geo-DR enabled towards a second namespace in a paired region within the same geography 😄

**Comment by SeanFeldman** [comment]
> I hope this doesn't cost you the job... but this is good example of why in production environment you should always use the Service Bus Premium with Geo-DR enabled towards a second namespace in a paired region within the same geography 😄

If only Geo-DR support data plane and not only meta plane... then it would be even useful 😀

**Comment by paolosalvatori** [comment]
@SeanFeldman maybe you didn't realize that in the meantime we released this guidance 😄 
https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-federation-overview

**Comment by atamu** [comment]
I hope you are not worried about me :), I was only joking about losing my job.
We use the Service Bus for lightweight messaging and are able to re-play anything that's lost due to fat-fingers within a few minutes.

I have to admit, I'm a lot more comfortable about locking my computer when the rush is on to get lunch.
Thanks for accepting my PR.

**Comment by paolosalvatori** [comment]
Of course, we were just joking 😄

**Comment by SeanFeldman** [comment]
> @SeanFeldman maybe you didn't realize that in the meantime we released this guidance 😄
> [docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-federation-overview](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-federation-overview)

I did happen to see that a few months ago. But from a customer perspective, that's a workaround, not an SB feature. It's as if you were asking a car manufacturer to add a feature and the manufacturer would send you to the hardware store to "bolt it on" yourself 😃

**Comment by paolosalvatori** [comment]
@SeanFeldman you have to have this conversation with @clemensv not with me 😄

**Pull request merged**
