### PR TITLE
Import Topic with CorrelationId Rules throws exception. - fixed

### PR DESCRIPTION
**Pull request by androdd**
I exported a topic with multiple subscriptions with CorrelationId filter rules. On importing it throws exception.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-PullRequest0395.122.build.608 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/29432754) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/08628180c1 by @androdd)

**Comment by ErikMogensen** [comment]
@androdd , due to the merging of another PR you need to resolve a merge conflict in a file for this PR.

**Comment by androdd** [comment]
I don't have write access so I can't resolve the conflicts.

**Comment by SeanFeldman** [comment]
@androdd conflicts should be resolved by re-basing your branch on top of the updated `develop`.

**Comment by androdd** [comment]
I don't have a branch. I forked the repo to be able to create a pull request.
The bug is fixed by changing one letter in a string - from "i" to "I". 
This whole stuff is taking too much time now. If somebody wants the import to work  please fix it. I don't need my name to be on this fix.

Best regards

**Comment by SeanFeldman** [comment]
When you forked the repo, you have created a branch under your repo called `develop`.
image. The link is https://github.com/androdd/ServiceBusExplorer. 

Alternatively, you could delete the clone/close this PR and redo the [change](https://github.com/androdd/ServiceBusExplorer/commit/36be6c07e51ac5f723e390697fc39c03902ecd18) to avoid conflicts in case rebasing is complicating matters. This is not about fame but helping. If you're still in, great. Otherwise, would you mind raising an issue instead of this PR so someone else could pick it up? Thank you, @androdd.

**Comment by ErikMogensen** [comment]
@androdd , the ImportExportHelper.cs file has been moved to another project and thus another location within the repo. If you want to I can create a PR with the changes you did.

**Comment by androdd** [comment]
Yes
Please, do. If this fix is still relevant at all.
Thank you.

**Comment by ErikMogensen** [comment]
Replaced by #398

**Pull request closed without merging**
