### PR TITLE
Fix coloring of subscription nodes

### PR DESCRIPTION
**Pull request by Greybird**
This PR ensures that subscription nodes can benefit from the coloring feature added previously.
This is something I missed in the original development.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 5.1.0-bugfix-subscriptions-colors.2.build.738 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/37043611) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/92aa10ad08 by @Greybird)

**Review by ErikMogensen — APPROVED** [review]
Thanks!

**Comment by SeanFeldman** [comment]
For the future, it's a good idea to attach a screenshot of what the change looks like.

Thank you, @Greybird.

**Review by SeanFeldman — APPROVED** [review]

**Comment by Greybird** [comment]
> 
> 
> For the future, it's a good idea to attach a screenshot of what the change looks like.
> 
> Thank you, @Greybird.

Sure, as this was a minor change, and pictures would have been quite similar to https://github.com/paolosalvatori/ServiceBusExplorer/pull/468, I did not include them, but for ui changes, I usually provide screenshots.

**Comment by paolosalvatori** [comment]
Thanks @Greybird @SeanFeldman @ErikMogensen

**Pull request merged**
