### PR TITLE
Add autoindent check control to MessageForm #195

### PR DESCRIPTION
**Pull request by gabrielgt**
* Allow resubmit a message with the same body it was received, without adding extra chars.

   image

* Updated Newtonsoft.Json library to 12.0.2

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-PullRequest0367.126.build.584 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/26412256) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/5390cf7cd2 by @gabrielgt)

**Comment by paolosalvatori** [comment]
@gabrielgt @SeanFeldman  before merging the PR, can you please confirm this different from #367?

**Comment by SeanFeldman** [comment]
@paolosalvatori I think you meant https://github.com/paolosalvatori/ServiceBusExplorer/pull/368
This concern was covered by https://github.com/paolosalvatori/ServiceBusExplorer/pull/368#issuecomment-517554416

**Comment by paolosalvatori** [comment]
whatever :) just let me know when I can squash and merge!

**Comment by gabrielgt** [comment]
Yes, #367 and #368 should be differente, but however #368 include #367, my fault, sorry :(
You can merge #367, and I will fix #368 to be independent, how it should be.

**Comment by paolosalvatori** [comment]
Thanks @gabrielgt and sorry for the delay, I was extremely busy in the last weeks

**Pull request merged**
