### PR TITLE
FixForDpiScalingInSubscriptionRules

### PR DESCRIPTION
**Pull request by kyle46**
#271
Turned off AutoScaling and adjusted Filter Type and Default content areas.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.1.0-PullRequest0277.282.build.497 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/20006959) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/1632377f6b by @kyle46)

**Comment by ErikMogensen** [comment]
I was unable to reproduce the issue in #273 on Win 10, I tried both 125% and 135% font scaling. @kyle46, which OS and display settings have you tested this on? 


Please also provide screenshots of before and after this fix.

I just want to be sure that it doesn't make things bad for other font scale settings.

**Comment by kyle46** [comment]
@ErikMogensen 
I was able to reproduce this on Windows 7 at 125% and 135%. On Windows 7 125% is the default where as Windows 10 100% is the default.

I'll provide screenshots on Monday. I don't have access to my Windows 7 machine until I get to work.

**Comment by kyle46** [comment]
@ErikMogensen Screenshots as requested. For some reason I wasn't able to reproduce the 150% version this time around. However the 125% version was still an issue. 
100% Release Version:
100 release version

100% PatchedVersion:
100 patched

125% Release Version:
125 release version

125% PatchedVersion:
125 patched

150% Release Version:
150 release version

150% Patched Version:
150 patched

**Comment by paolosalvatori** [comment]
I approved and merged the PR, but let's test this change on Windows 10 please

**Comment by ErikMogensen** [comment]
I have verified this on Win 10 on 100%, 125% and 135%. It looks great on all of them.

Great work @kyle46!

**Comment by paolosalvatori** [comment]
Thanks @kyle46 :)

**Pull request merged**
