### PR TITLE
Deleted root app.config

### LINKED ISSUE #462: There are two app.config files
There are two app.config files which must be wrong.

### PR DESCRIPTION
**Pull request by ErikMogensen**
Fixes #462

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:x: [Build ServiceBusExplorer 4.2.0-RemoveRootAppConfig.74.build.721 failed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/35941363) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/7660712fa2 by @ErikMogensen)

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-RemoveRootAppConfig.75.build.722 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/35941544) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/3d9022bf30 by @ErikMogensen)

**Review by paolosalvatori — APPROVED** [review]

**Comment by paolosalvatori** [comment]
@ErikMogensen  @SeanFeldman another approval is necessary to merge the PR

**Review by SeanFeldman — APPROVED** [review]

**Comment by ErikMogensen** [comment]
Paolo, I am not allowed to approve my own PR.

**Comment by paolosalvatori** [comment]
Thanks @SeanFeldman for approving the PR :)

**Pull request merged**
