### PR TITLE
Made all of the background blue on the Options window

### LINKED ISSUE #269: The background on the Options window should be blue
That should make it look more like the other Service Bus Explorer windows.

### PR DESCRIPTION
**Pull request by ErikMogensen**
This is the same style as most of the other dialog windows. Fixes #269.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.1.0-PullRequest0273.280.build.494 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/19891899) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/b4bf685107 by @ErikMogensen)

**Comment by paolosalvatori** [comment]
Good morning @ErikMogensen , can you please add a picture to see the final look and feel, then I'll approve the PR. Thanks :)

**Comment by ErikMogensen** [comment]
Certainly.

This is how it looks like before this PR:

image

and this is how it looks like after the PR:

image

Looking at it more closely I see that it would look better if there was slightly more distance between the top of the Setting group control and the controls inside it.

**Comment by paolosalvatori** [comment]
Definitely approved. Thanks!

**Pull request merged**
