### PR TITLE
Update README.md to support chocolatey

### PR DESCRIPTION
**Pull request by Nate-Wilkins**

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.0.95-PullRequest0129.2.build.250 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/build/4.0.95-PullRequest0129.2.build.250) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/ba4c6a44bd by @Nate-Wilkins)

**Comment by Nate-Wilkins** [comment]
@paolosalvatori I don't have any permissions to push the chocolatey package for this so it'll point to whatever is currently on chocolatey. Let me know when you add me as a choco maintainer.

**Comment by paolosalvatori** [comment]
@Nate-Wilkins let me know what do I need to do to promote you choco maintainer.

**Comment by Nate-Wilkins** [comment]
@paolosalvatori cool! You have to add me as a maintainer on the left hand side of the chocolatey package when you're logged in.

**Comment by paolosalvatori** [comment]
Absolutely. Said that, I'd prefer the script to be part of this project rather than on your GitHub account. Would you mind moving your https://github.com/Nate-Wilkins/chocolatey-packages/blob/master/automatic/servicebusexplorer/update.ps1 script under this project via a PR? Thansk :)

**Comment by Nate-Wilkins** [comment]
Oh yeah sure absolutely! I'll automate it over on this side, should be a lot easier too.

**Comment by paolosalvatori** [comment]
Thanks @Nate-Wilkins :)

**Pull request merged**
