### PR TITLE
Persist the message text

### LINKED ISSUE #588: "Hi mate, how are you?" cannot be changed and persisted
First of all - thank you for this _amazing_ tool! It's so super-useful.

My comment is a very trivial one, but I thought I'd raise it anyway. It's just about the "Hi mate, how are you?" text that's there by default when trying to send a new message. Azure Service Bus Explorer looks a very well done, professional-quality tool. And this might just be me, but that message just looks silly. When using it in a screen-share - I always feel I have to explain to other people in the call that it's not my message - it's for some reason the default message. It feels like an odd thing to have in an other-wise, very well polished application. It just feels totally out of place.

### PR DESCRIPTION
**Pull request by ErikMogensen**
Fixes #588, about the "Hi Mate..." that could not be changed.

Added a new class that is used a a base class for the classes used for testing messaging entities.

Since it changes the same files as the other pull request I created some days ago this one is created from that branch to lessen the risk of merge conflicts. So it is easier to review this one after that other PR has been merged.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:x: [Build ServiceBusExplorer 893 failed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/41523994) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/5d20f0ec2c by @ErikMogensen)

**Comment by ErikMogensen** [comment]
I see that the build error is:
`gitversion :   ERROR [11/14/21 12:15:03:72] An unexpected error occurred:`

It may be that GitVersion couldn't handle a feature branch based on another feature branch. I'll wait with the troubleshooting until that other PR is merged.

**Comment by paolosalvatori** [comment]
@ErikMogensen ping me via email when you have fixed the issue and I'll approve the PR!

**Comment by SeanFeldman** [comment]
:x: [Build ServiceBusExplorer 896 failed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/41538148) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/31b24f74b7 by @ErikMogensen)

**Comment by ErikMogensen** [comment]
Replaced by #604 since Gitversion didn't work with this one.

**Pull request closed without merging**
