### PR TITLE
Fix sending files

### PR DESCRIPTION
**Pull request by ErikMogensen**
This fixes the initial issue in  #431 by skipping the test for an empty message text and adding an explanation to the GUI that you have to change the Message Count if you want to all of the selected files if you have selected multiple files.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 5.1.0-FixSendingFiles.15.build.791 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/37418216) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/38bc425ef5 by @ErikMogensen)

**Comment by ErikMogensen** [comment]
The updated GUI for the forms for testing topics and queus now look like this when the Files tab is selected.
image

**Review by SeanFeldman — APPROVED** [review]

**Review by paolosalvatori — APPROVED** [review]

**Comment by paolosalvatori** [comment]
Thanks @ErikMogensen, an alternative solution could be the opposite: if someone select more messages on the UI, we automatically set the value of the Message Count field equal to the number of the selected messages. :)

**Comment by Maverick1983** [comment]
Sorry, but for EventHub not working yet?

**Comment by ErikMogensen** [comment]
@Maverick1983, it was just fixes in pr #603.

**Comment by Maverick1983** [comment]
> @Maverick1983, it was just fixed in pr #603.

Thanks!

**Pull request merged**
