### PR TITLE
Log exception when listing entities in the namespace

### PR DESCRIPTION
**Pull request by bjorn-ali-goransson**
Hello,

I'm dealing with a SB connection where we do not have access to list subscriptions or topics.

This doesn't really work, but an initial hurdle is that establishing the connection (specifically listing the subscriptions and "event hubs") seems to get into some kind of deadlock. At least now I get an exception.

image

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 5.1.0-add-async-to-listing-methods.27.build.834 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/39166019) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/0953e8649c by @bjorn-ali-goransson)

**Comment by bjorn-ali-goransson** [comment]
Perhaps a solution to my ultimate problem would be to manually enter the subscription and topic here, in two new fields?

(I'm not saying it will result in a good UX 😆)

**Review by ErikMogensen — APPROVED** [review]
This is useful for other changes too.

**Comment by ErikMogensen** [comment]
I recognize this problem. I think having another type of Connect would  work. Perhaps one menu item called "Connect to namespace" and another called "Connect to entity", where you only get access to one entity.

**Review by SeanFeldman — APPROVED** [review]

**Comment by SeanFeldman** [comment]
Thank you @bjorn-ali-goransson.

**Comment by paolosalvatori** [comment]
Thanks for the PR @bjorn-ali-goransson ❤️

**Comment by bjorn-ali-goransson** [comment]
Thank you back for making this awesome tool!

**Pull request merged**
