### PR TITLE
Add ScheduledEnqueueTimeUtc and LockedUntilUtc to the DataGridViews and update cellformatting to include seconds for DateTime values.

### PR DESCRIPTION
**Pull request by qsdfplkj**

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 5.1.0-showseconds.25.build.820 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/38642662) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/84997116eb by @)

**Comment by ErikMogensen** [comment]
@qsdfplkj, please post one or more screenshots of the GUI changes.

**Comment by qsdfplkj** [comment]
image

**Comment by ErikMogensen** [comment]
I agree. ScheduledEnquedTime should be at the end. LockedUntil time would be nice to have there also, as you mentioned, since it is easily overlooked as a cause for a message not being picked up. However I am concerned about the screen estate. On my screen it is no place left without Scheduled Time. I wonder if a horizontal scrollbar would be the solution.

It would also be nice if the scheduled time wasn't shown if it is not scheduled. Are the messages in your screenshot scheduled?

**Comment by paolosalvatori** [comment]
Hi @qsdfplkj please let us know when you have done the changes that you and @ErikMogensen  suggested. In addition, if you want to make it possible to specify a schedule delay in seconds, minutes, or hours, you should also change the UI in the send form for queues and topics and replace the textbox with a textbox + dropdownlist with units of time (seconds, minutes, hours) and change the code to calculate the scheduled time.

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 5.1.0-showseconds.27.build.824 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/38684957) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/1e6432ae39 by @)

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 5.1.0-showseconds.28.build.825 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/38685015) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/9fcddda2cd by @)

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 5.1.0-showseconds.29.build.826 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/38685060) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/d7a86f24f8 by @)

**Comment by qsdfplkj** [comment]
> Hi @qsdfplkj please let us know when you have done the changes that you and @ErikMogensen suggested. In addition, if you want to make it possible to specify a schedule delay in seconds, minutes, or hours, you should also change the UI in the send form for queues and topics and replace the textbox with a textbox + dropdownlist with units of time (seconds, minutes, hours) and change the code to calculate the scheduled time.

The columns have been committed.

Regarding the dropdownlist there is the ServiceBus TimeSpanControl but it requires a layout change because it's too wide.
image 
Though I could also replace the textbox with a maskedTextBox but then again maybe seconds is enough.
image

Still would be nice is someone could adds a typeconverter that displays seconds on the propertygrid.

**Comment by paolosalvatori** [comment]
@qsdfplkj sorry for the delayed answer, could you please let us see what is the final layout if you replace the TimeSpanControl with a MaskedTextBox? I've seen the picture above but I'm not fully convinced that a user could understand what enter and in which format. Thanks!

**Pull request closed without merging**
