### PR TITLE
Import Topic with CorrelationId Rules throws exception 

### PR DESCRIPTION
**Pull request by ErikMogensen**
This PR replaces #395 implemented by @androdd. The reason for me implementing it is that there was a major restructuring in PR #381 that caused this PR to get some merge conflicts.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-PullRequest0398.126.build.613 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/29562417) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/a0e4cf0582 by @ErikMogensen)

**Comment by ErikMogensen** [comment]
@androdd, please review this.

**Comment by SeanFeldman** [comment]
@paolosalvatori we need a 2nd approver to merge and wrap up release 4.1.113

**Comment by Greybird** [comment]
Hello,
Is there something blocking in the content of this PR? Is there some way to help on this?
Would really like to see a version released 😊

**Comment by ErikMogensen** [comment]
Thanks @Greybird , the develop branch contains code using the new SDKs which makes some issues that are still not solved. and in my opinion they have to be fixed before releasing. I labeled those issues RequiredForV5.

**Pull request merged**
