### PR TITLE
All project files should be in sdk style

### LINKED ISSUE #116: Convert solution to use the new CSPROJ format
The new csproj format is cleaner, smaller, better package and reference management, multi-targeting, etc.

Some reading material:
- [Old csproj to new csproj: Visual Studio 2017 upgrade guide](http://www.natemcmaster.com/blog/2017/03/09/vs2015-to-vs2017-upgrade/) bit dated, but still good.
- [Additions to the csproj format for .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj)

### PR DESCRIPTION
**Pull request by ErikMogensen**
Converted the remaining projects to SDK style.

This fixes #116

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:x: [Build ServiceBusExplorer 5.1.0-main-use-sdk-style-project.43.build.855 failed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/39763149) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/ca57c2e513 by @ErikMogensen)

**Comment by SeanFeldman** [comment]
:x: [Build ServiceBusExplorer 5.1.0-main-use-sdk-style-project.44.build.856 failed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/39763276) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/ac178afb1a by @ErikMogensen)

**Comment by SeanFeldman** [comment]
:x: [Build ServiceBusExplorer 5.1.0-main-use-sdk-style-project.45.build.857 failed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/39763362) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/e9605d4cf1 by @ErikMogensen)

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 5.1.0-main-use-sdk-style-project.46.build.858 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/39775135) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/6d1294e1dd by @ErikMogensen)

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 5.1.0-main-use-sdk-style-project.47.build.859 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/39775194) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/5dc6caed6d by @ErikMogensen)

**Review by SeanFeldman — APPROVED** [review]

**Review by paolosalvatori — APPROVED** [review]

**Pull request merged**
