### PR TITLE
Fix copying behavior of properties when resubmitting messages

### PR DESCRIPTION
**Pull request by gabrielgt**
When resubmitting several messages in batch mode, properties should be copied when cloning. But when resubmitting only one message, properties should not, because the user can choose what properties he wants to copy through Message Custom Properties GroupBox.

   image

So, clone depends on resubmitting one or more messages.
In any case, properties with name "DeadLetterReason", "DeadLetterErrorDescription" and "NServiceBus.Transport.Recovery", should never be copied.

Issue #344 should be solved with this PR.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-PullRequest0368.127.build.585 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/26414743) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/f5f6e30e91 by @gabrielgt)

**Comment by SeanFeldman** [comment]
It appears this PR has some changes identical to another PR, #367.
Should these two be merged together?

**Comment by paolosalvatori** [comment]
@SeanFeldman @gabrielgt Please let me know how you intend to proceed. I'll be on vacation the next two week, returning the 20th.

**Comment by SeanFeldman** [comment]
@paolosalvatori the https://github.com/paolosalvatori/ServiceBusExplorer/pull/368#issuecomment-517554416 should be addressed. I'm back on August 6th :)

**Comment by gabrielgt** [comment]
I will do it in a new PR.

**Pull request closed without merging**
