### PR TITLE
Add proxy configuration UI and logic

### PR DESCRIPTION
**Pull request by Greybird**
This PR is a proposal aiming to solve the issue #343 
Rework of #430 with tabs merged since then.

# Screenshots
image

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:x: [Build ServiceBusExplorer 4.2.0-proxy-settings.59.build.651 failed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/31556553) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/f4ddb2a25a by @)

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-proxy-settings.59.build.652 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/31556590) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/143c585093 by @)

**Comment by paolosalvatori** [comment]
Thanks a lot @Greybird! Could you please add this change to the #436. Sorry, but we crossed PRs :(

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-proxy-settings.71.build.676 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/31617953) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/ea5fb05942 by @)

**Comment by Greybird** [comment]
Hi @paolosalvatori,

Sure, here it is. I'm really looking forward to v5 release, so anyway I can help 😄 

I did not recognize your numbers on spacing/locations, but I think it might be related to either controls hierarchy and/or other unit issues.
However, I made sure the sizes and location match thoses from other tabs, so this should be ok now.

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-proxy-settings.61.build.681 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/31651635) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/da008d4356 by @)

**Comment by paolosalvatori** [comment]
Thanks @Greybird I mean that all label starts from 32, 48

this.lblXXXX.Location = new System.Drawing.Point(32, 48);

while the related control starts from 520, 48:

this.txtXXXX.Location = new System.Drawing.Point(520, 48);

The next one will be 60 points below:

this.lblYYYY.Location = new System.Drawing.Point(32, 48);
this.txtYYYY.Location = new System.Drawing.Point(520, 48);

and so on :) 

It looks like your OptionForm.Designer.cs does not integrate my recent changes :) could you use the most recent version as a base for your branch? I just modified the OptionForm.cs and OptionForm.Designer.cs. Thanks :)

**Comment by Greybird** [comment]
Hello @paolosalvatori ,

Sorry, I was not clear enough about the issue.

Actually, I cannot get the values you are asking for, because as soon as I save the UI, the designer changes all the values.
However, if you look at the form in the designer, you will see it is conforming to the ui.

however, I might have found the root cause for this:
`this.AutoScaleDimensions = new System.Drawing.SizeF(12F, 25F);`
switches to
`this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);`
When I'm saving the designer.
Are you by chance using a non-100% Dpi on your development machine ?
I think this might be related.

**Comment by Greybird** [comment]
You just merged the PR, do you still need some action from me ?
On the side note, I just noticed the Paint event (like `tabPageGeneral_Paint`)  was missing for the Receiving tab (and the proxy too, sorry for this).

**Comment by paolosalvatori** [comment]
I did a mistake, I wanted to merge #435 let me download the develop branch and check the result

**Comment by paolosalvatori** [comment]
All good @Greybird thanks!

**Pull request merged**
