### PR TITLE
Changed Look & Feel of the Options Form

### PR DESCRIPTION
**Pull request by paolosalvatori**
This pull request changes the look & feel of the Options form:
 - Decreases the size of the dialog form
 - Changed location and size of controls
 - Added borders to dropdownlist controls

Options

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-borders.58.build.656 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/31583269) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/d6a68cde21 by @paolosalvatori)

**Comment by paolosalvatori** [comment]
I didn't realize that I had this folder. Let me remove it.

**Comment by paolosalvatori** [comment]
Please look at the PR now, thanks @ErikMogensen  for the heads up!

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-borders.59.build.659 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/31597427) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/9e89a84590 by @paolosalvatori)

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-borders.60.build.661 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/31597822) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/c920af8cae by @paolosalvatori)

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-borders.61.build.663 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/31607169) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/efdd048940 by @paolosalvatori)

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-borders.62.build.665 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/31607452) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/efdd048940 by @paolosalvatori)

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-borders.63.build.667 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/31607676) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/e1148242ea by @paolosalvatori)

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-borders.64.build.669 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/31607748) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/fed25a4d25 by @paolosalvatori)

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-borders.68.build.671 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/31607806) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/6604fa7426 by @paolosalvatori)

**Comment by paolosalvatori** [comment]
Thanks @ErikMogensen I had some old files in the folder :| Try now

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-borders.68.build.673 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/31607824) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/fc8c403f74 by @paolosalvatori)

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-borders.68.build.675 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/31607842) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/1e92cc248b by @paolosalvatori)

**Pull request merged**
