### PR TITLE
Re-submit a single message with binary content created with Azure.Messaging.ServiceBus nuget package

### PR DESCRIPTION
**Pull request by KinNeko-De**
I found out that the issue discussed in #712 only occurs when Azure.Messaging.ServiceBus is used.
I added UnitTest to show that the issue does not occur if you use Windows.AzureService.
I failed to reproduce exactly the error. I added a test that somehow emulates the error behavior. I do have not enough knowledge of what was changed between the two APIs. Also, the current Protobuf Nuget Package does not support 4.6.2 so i had to add the Protobuf message as a byte array :(

I ended up adding an additional menu item to resubmit a single message without changing the content.
I reused the code from the resubmit of multiple messages.
But that is just a workaround.

I manually tested re-submitting in Azure ServiceBus Queue and Topic and in both cases DLQ-Messages.
I was not able to manually test Azure Event Grid because I have no test environment.

Finally, I updated NUnit3TestAdapter to the newest version to locally run tests.

### CODE REVIEW

**Comment by ErikMogensen** [comment]
Please provide screen shots of the new GUI parts.

**Comment by KinNeko-De** [comment]
Before:
servicebusexplorer_before

After:
servicebusexplorer

Multiple Messages are unchanged:
servicebusexplorer_multiple

**Review by ErikMogensen — APPROVED** [review]
Really appreciate that you created unit tests. Thank you!

Personally I think that the new Resubmit menu item should be on top of "Repair and resubmit".

**Comment by KinNeko-De** [comment]
Hey..
I am not completely sure what I have to do now.
Do you wait for me to move the menu item to the first place?

**Comment by ErikMogensen** [comment]
No need to do anything @KinNeko-De. I'd prefer if @paolosalvatori or @SeanFeldman also reviewed the PR.

**Comment by KinNeko-De** [comment]
@ErikMogensen Thx :) I was confused because the bot marked my issue as stale and 'wontfix' even if there is an open pull request.
I have no problem to wait :)

**Pull request merged**
