### PR TITLE
Changed Padding, Location and similar properties to get the scrollbars back. Fix #224

### LINKED ISSUE #224: Scrollbars are missing
The three scrollbars are missing from the main window. This has happened in one of the later commits.

### PR DESCRIPTION
**Pull request by ErikMogensen**
This is for fixing #224. 

I noticed that any small change in the Designer GUI to the MainForm will cause this issue to come back. I'll create an issue for that since it makes developing anything involving the UI on the MainForm difficult.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.1.0-PullRequest0225.226.build.409 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/build/4.1.0-PullRequest0225.226.build.409) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/dc7a0782e8 by @ErikMogensen)

**Comment by SeanFeldman** [comment]
I honestly don't know how to review it.
When  `Size(495, 701)` changes to `Size(372, 570)` it has no meaning to me 😃
Will defer to others.

**Comment by tomkerkhove** [comment]
Same here @SeanFeldman. @ErikMogensen did you try this on a few machines?

So the whole issue that caused this was the designer in VS?

**Comment by ErikMogensen** [comment]
@tomkerkhove , I tested this on three machines. One of the machines used a High dpi display and it worked before the change and after the change too :)


Yes, I did a minor thing in the designer on the MainForm and caused lots of changes, which had the effect of most scrollbars going away. I created an issue since for this, #226  since I did not fix the root cause.

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.1.0-PullRequest0225.234.build.410 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/build/4.1.0-PullRequest0225.234.build.410) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/d3a39a74c0 by @ErikMogensen)

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.1.0-PullRequest0225.235.build.411 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/build/4.1.0-PullRequest0225.235.build.411) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/f9a1c7bb9f by @ErikMogensen)

**Comment by ErikMogensen** [comment]
I was unable to work without the scrollbars so the commits I did for the Removing metrics issue ended up in this PR. Could/should I have done it differently?

**Pull request merged**
