### PR TITLE
Fix long delay when creating invalid entity

### PR DESCRIPTION
**Pull request by apjanke**
Partially addresses #327.

Currently, when you attempt to create an Event Hub in a Namespace that is for Queues/Topics, or vice versa, the UI will freeze for about 30 seconds, before spewing some errors to the log. This is because the creation attempt is retried 10 times, even though this isn't a transient error.

This PR improves UI responsiveness by changing `RetryHelper` to consider `QuotaExceededException` (which is what happens in this case) to be non-transient, and not retry it.

Does not fix the UI freeze when creating Relays in a non-Relay namespace, because that throws a different `AggregateException`, which I'm not comfortable special-casing to be non-transient in this PR, unless y'all give that an explicit thumbs-up.

You could go even further along this route: `RetryHelper` considers the generic `Exception` to be transient and retries it. I think maybe it should be the other way around: consider generic `Exception` to be non-transient, and only retry on special-cased exceptions that are known to be probably transient.

### CODE REVIEW

**Comment by apjanke** [comment]
> I just saw in the source code that is is already doing the IsTransient check for MessagingException, which QuotaExceeded inherits from.

Are you sure about that? Looking at the [`QuotaExceededException` docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.quotaexceededexception?view=azure-dotnet), it looks like `QuotaExceededException` inherits from `Microsoft.Azure.ServiceBus.ServiceBusException`, which is unrelated to `MessagingException`. `ServiceBusException` has an `IsTransient` property. So instead of handling `QuotaExceededException` specially, I think we need to add a `catch` for `ServiceBusException`, and have it use the same logic as the existing `catch` for `MessagingException`.

**Comment by apjanke** [comment]
Nevermind, you're right: _this_ `QuotaExceededException` (`Microsoft.ServiceBus.Messaging.QuotaExceededException`) is in fact derived from `Microsoft.ServiceBus.Messaging.MessagingException`. That [`Microsoft.Azure.ServiceBus.QuotaExceededException`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.quotaexceededexception?view=azure-dotnet) I was looking at must be from a different SDK or a different version of the SDK.

I'll take your suggested approach instead.

**Comment by ErikMogensen** [comment]
Yes, It is easy to mix the old and the new SDKs. The documentation is sometimes not clear if it is for the old, the new or both SDKs. Anyway:

- Microsoft.ServiceBus.dll: old one based on Full .NET Framework
- Microsoft.Azure.ServiceBus.dll: new one based on .NET Standard

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-PullRequest0330.104.build.555 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/23122669) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/d6f6841a6c by @apjanke-ccs)

**Comment by apjanke** [comment]
Aha! The issue is that the RetryFunc* variants (as opposed to RetryAction*) are only catching `MessagingCommunicationException`, not `MessagingException`, so `MessagingException`s, including `QuotaExceededException`, are not getting tested for `IsTransient` before doing the retry.

I've amended this commit to just add `catch (MessagingException ex)` blocks to the RetryFunc* variants. No special handling for `QuotaExceededException` now.

**Comment by paolosalvatori** [comment]
Thanks @apjanke!

**Pull request merged**
