### PR TITLE
Show exception when entities cannot be retrieved

### LINKED ISSUE #205: SBE doesn't show Topics and Queues whilst Azure portal shows them
# Problem

Suddenly, I couldn't retrive the list of topics and queues from Azure using SBE. 
SBE logs show:
<15:15:17> The application is now connected to the sb://_MyNamespace_.servicebus.windows.net/ service bus namespace.
<15:15:17> MessagingFactory successfully created

but the right hand side tree is empty, although I can see the queues and topics in Azure web portal.

### PR DESCRIPTION
**Pull request by SeanFeldman**
Fixes #205 

I'm not entirely sure on the syntax in the messages for Relays, Notification Hubs, and EventHubs.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.1.0-PullRequest0207.209.build.390 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/build/4.1.0-PullRequest0207.209.build.390) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/24bc2e191a by @SeanFeldman)

**Comment by SeanFeldman** [comment]
Thanks @tomkerkhove.
Given we're fully dispersed, I'd give a PR to reach 48h mark and merge then.

**Comment by ErikMogensen** [comment]
It looks good to me too - clever use of the When keyword!  However, I think the word retrieved should be inserted into the messages for Notification Hubs and Relays, like you had on the messages for the other service types. 

I would also rename WriteToLogFormatted to WriteToLogSynced or something like that since it does not do any different formatting than WriteToLog. Lastly I would rename FilterOutExceptionAndLog to just FilterOutException since it does not do any logging.

**Comment by SeanFeldman** [comment]
- `WriteToLogFormatted` removed as it was redundant.
- `FilterOutExceptionAndLog` renamed

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.1.0-PullRequest0207.210.build.392 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/build/4.1.0-PullRequest0207.210.build.392) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/8fe8f3f668 by @SeanFeldman)

**Pull request merged**
