### PR TITLE
Upgraded Event hubs SDK

### PR DESCRIPTION
**Pull request by ErikMogensen**
Upgrade the Event Hubs SDK from Microsoft.Azure.EventHubs to Azure.Messaging.EventHubs.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 5.1.0-UpgradeEventHubsSdk.2.build.740 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/37044951) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/f654ae5956 by @)

**Review by SeanFeldman — APPROVED** [review]

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 5.1.0-UpgradeEventHubsSdk.7.build.748 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/37068959) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/6c99cab0b5 by @)

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 5.1.0-UpgradeEventHubsSdk.8.build.749 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/37069251) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/84828c04ae by @)

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 5.1.0-UpgradeEventHubsSdk.9.build.750 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/37070600) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/56135edac8 by @ErikMogensen)

**Review by paolosalvatori — APPROVED** [review]

**Comment by paolosalvatori** [comment]
@SeanFeldman can you please approve the change when you have time? Thanks :)

**Review by SeanFeldman — APPROVED** [review]

**Pull request merged**
