### PR TITLE
Allow configuring AMQP Web Sockets usage

### LINKED ISSUE #396: Support for TransportType.AmqpwebSockets
The recently merged PR #381 includes changes that cause ServiceBusExplorer to use the new SDKS for ServiceBus, Relay and EventHubs. Currently the only functionality that is using the new SDKs is the purging of ServiceBus messages.

However the new functionality does not have support for setting the TransportType to [AmqpWebSockets](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.transporttype?view=azure-dotnet), which is required if you are connecting to ServiceBus through a proxy. 

TransportType in the new client translates to ConnectivityMode in the old client, but there is no automatic mode in the new client which would correspond to ConnectivityMode = AutoDetect. To handle that the GUI needs to be changed. Preferably it should support configuring the proxy settings too. This is brought up in issue #343.

**The workaround for this is to just Receive and Delete the messages.**

### PR DESCRIPTION
**Pull request by Greybird**
This PR aims to fix #396
It also replugs all the event handlers lost on the OptionForm

# Screenshots
Amqp setting is now enabled:
image

Amqp settings and Connectivity mode are now taken from the options:
image

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-amqp.59.build.653 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/31557794) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/95ab4a0c27 by @)

**Comment by paolosalvatori** [comment]
Thanks @Greybird :) We crossed PRs and I already restored event handlers in the new version of the Options form :) See #436

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-amqp.70.build.677 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/31618027) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/dd6f989af1 by @)

**Comment by Greybird** [comment]
Sure, here it is. I rebased on `borders` branch.

I did not recognize your numbers on spacing/locations you gave me, but like in #436, I think it should be consistent.
Note that this PR will conflict with #436, but the merge will impact two files, and be really easy

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-amqp.60.build.679 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/31651618) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/d90470c153 by @)

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-amqp.60.build.680 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/31651629) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/a3f48e4c49 by @)

**Comment by paolosalvatori** [comment]
We need someone else (@SeanFeldman  or @ErikMogensen) to review and approve. I checked the the OptionsForm.Designer.cs and it looks this version includes my changes :)

**Comment by Greybird** [comment]
Just resolved the merge conflict, sorry @SeanFeldman , @ErikMogensen , @paolosalvatori , reviews have been reset as a consequence...

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-amqp.62.build.683 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/31659037) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/37bdd2c67a by @Greybird)

**Pull request merged**
