### PR TITLE
app.manifest with DPIaware enabled

### PR DESCRIPTION
**Pull request by judgewest2000**
DPI aware enabled by default

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-PullRequest0362.116.build.579 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/25850747) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/eaac25063a by @judgewest2000)

**Comment by ErikMogensen** [comment]
@judgewest2000 , this is most likely a good thing for the GUI, but I don't understand what it will do. Please create an issue describing the problem this solves or put more information in this PR.

When searching for information regarding this I came across question on StackOverFlow; https://stackoverflow.com/questions/23551112/how-can-i-set-the-dpiaware-property-in-a-windows-application-manifest-to-per-mo. It mentions some related settings. Do you think those should be included too?

**Comment by beaubgosse** [comment]
Here are all the bugs I could find. I don't know if there is a better way to post this.

OptionsCheckboxCutOff
OptionsCheckboxCutOff

QueueNamesTooClose
QueueNamesTooClose

TextBoxMissingDefineFilterMessagesView
TextBoxMissingDefineFilterMessagesView

AnyAlertMessageIsCutoff
AnyAlertMessageIsCutoff

defaultColumnSpacingTopicAuthRules
defaultColumnSpacingTopicAuthRules

ResubmitDoesntFillWindow
ResubmitDoesntFillWindow

spacingUnderTitles
spacingUnderTitles

SpacingUnderTitles
SpacingUnderTitles-2

SpacingUnderTitles
SpacingUnderTitles-3

subscriptionRules
subscriptionRules

**Comment by ErikMogensen** [comment]
Is that before or after applying the code in this PR?

**Comment by beaubgosse** [comment]
These are the bug after applying the code in the PR. Seems like most would be fixed with the proper spacing under text. I've never developed in WinForms so I would kinda be guessing how to fix these.

**Comment by paolosalvatori** [comment]
@ErikMogensen @SeanFeldman @beaubgosse @judgewest2000 how do you want to proceed with this PR? Do you want to:
 - close it
- refactor the code
- merge it?

**Comment by SeanFeldman** [comment]
@paolosalvatori, if my understanding is correct, @judgewest2000 has enabled high DPI support with this PR and @beaubgosse has identified some issues with the UI as a result of the PR.

Either @judgewest2000 can look into that or someone with Windows Forms knowledge could give a hand. Given it's almost a year old PR, I don't know if the original author is still willing to work on this item or no. If there's no follow up from the author or any volunteer within a week, I'd say close it.

**Comment by paolosalvatori** [comment]
Ok, I'll close this PR for now, thanks everyone!

**Pull request closed without merging**
