### PR TITLE
Updated ServiceBus nuget package, targeted AnyCPU, targeted .Net 4.6.1

### PR DESCRIPTION
**Pull request by vonlar**
Changes made:

- I've updated the ServiceBus nuget package.  
- Created a new Configuration for AnyCPU
- Changed the output to AnyCPU 
- Removed the preference for 32 bit
- Updated the target .Net framework to 4.6.1

Changes not made:
- Increment version number
- Have the MSI install to 'Program Files' instead of 'Program Files (x86)'

### CODE REVIEW

**Comment by SeanFeldman** [comment]
@paolosalvatori you should have increased the version as it's not the same 3.4 as it was before 😉

**Comment by paolosalvatori** [comment]
I realized that and increased the version right yesterday to 3.4.0 :)

**Comment by vonlar** [comment]
Any way to get the installer to put it in "Program Files" instead of "Program Files (x86)"?

**Comment by paolosalvatori** [comment]
I don't know... I didn't make the installer :-)

**Pull request merged**
