### PR TITLE
Make it possible to generate fresh MessageId on submit

### LINKED ISSUE #145: [Feature] It should be possible to regenerate a fresh MessageId when resubmitting a message.
The form used to fix and resubmit the messages should have a checkbox to allow the user to specify if the resubmitted messages should have a new MessageId or use the existing one.

### PR DESCRIPTION
**Pull request by lenardg**
This change resolves #145. I added a new checkbox near the submit button. When checked, the submit process will generate new IDs for the message(s).

Not the best solution from a user experience standpoint, but after thinking about this quite a while this is the best solution I came up with without making larger changes to the UI.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.1.0-PullRequest0156.131.build.313 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/build/4.1.0-PullRequest0156.131.build.313) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/090e9abc31 by @lenardg)

**Comment by tomkerkhove** [comment]
Hi @lenardg, thanks for this PR. We will review it but would you mind changing it to go to develop instead of master please?

**Comment by lenardg** [comment]
Sure @tomkerkhove ! I was debating which branch to base it off, but did not find proper instructions anywhere. Sorry about this!

**Comment by tomkerkhove** [comment]
Thanks for raising that - Created #157 for this

**Comment by paolosalvatori** [comment]
@lenardg thanks for the the update

**Comment by SeanFeldman** [comment]
Assigned to milestone 4.0.105

**Pull request merged**
