### PR TITLE
Programmatically set connection limit instead of using configure

### PR DESCRIPTION
**Pull request by jeremy001181**
Details can be found in #254

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.1.0-PullRequest0255.269.build.466 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/build/4.1.0-PullRequest0255.269.build.466) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/6c62d4f4e4 by @)

**Comment by ErikMogensen** [comment]
Since SBE is sometimes used for performance testing my concern is that 50 connections won't be enough and by hardcoding it, it becomes cumbersome to change it . I see little harm in increasing it to 200. It won't affect anything unless the connections are actually used.

**Comment by SeanFeldman** [comment]
What happened to "increasing to 200 connections" and 👍s ?
image

My understanding it should have been done on PR _prior_ to merging it.

**Comment by paolosalvatori** [comment]
@SeanFeldman true, but I've seen that all of you approved the PR, so I merged it. @jeremy001181 could you please create another PR to increase the max number of connections to 200? Thanks!

**Comment by jeremy001181** [comment]
@paolosalvatori yeah ,there you go #257

**Pull request merged**
