### PR TITLE
[WIP] Generate assembly version locally and on build server

### PR DESCRIPTION
**Pull request by SeanFeldman**
This PR will allow assembly version to be generated locally (based on git info) and on the build server.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.0.86-PullRequest0108.6.build.184 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/build/4.0.86-PullRequest0108.6.build.184) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/5dda8273ca by @SeanFeldman)

**Comment by SeanFeldman** [comment]
:x: [Build ServiceBusExplorer 186 failed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/build/186) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/c982eee374 by @SeanFeldman)

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.0.86-PullRequest0108.7.build.189 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/build/4.0.86-PullRequest0108.7.build.189) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/8a0a692b16 by @SeanFeldman)

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.0.86-PullRequest0108.7.build.191 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/build/4.0.86-PullRequest0108.7.build.191) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/b862f8d00b by @SeanFeldman)

**Comment by SeanFeldman** [comment]
Oh no... @paolosalvatori, this is a WIP
Can you please revert the commit from the master?

**Comment by paolosalvatori** [comment]
How... deleting the branch?

**Comment by SeanFeldman** [comment]
Now, reverting the merge on the master...


Kind regards,
Sean Feldman

**Comment by paolosalvatori** [comment]
Ok... should I merge or not your request now?

**Comment by SeanFeldman** [comment]
Nope, it's a WIP. I'll ping you when it's ready :)


Kind regards,
Sean Feldman

**Comment by paolosalvatori** [comment]
Eh eh... yes... I think it's better this way :) Thanks @SeanFeldman :)

**Comment by SeanFeldman** [comment]
I've reverted changes.

**Comment by SeanFeldman** [comment]
In the about dialog, the version is still showing as 1.0.0... that's an error ;)

**Pull request merged**
