### PR TITLE
Exported JSON cannot be imported

### LINKED ISSUE #586: Exported brokered message cannot be imported properly to be sent to a queue
**Service Bus Explorer version: 5.0.4**

I saved a brokered message in json format (e.g. from a topic). The contents look like this (some properties redacted):

```
{
  "body": {
    *someJsonBody*
  },
  "contentType": "application/json",
  "correlationId": "286382a8-2103-4d13-8f1f-ad830080e1c9",
  "deadLetterSource": null,
  "deliveryCount": 1,
  "enqueuedSequenceNumber": 117004163,
  "enqueuedTimeUtc": "2021-08-13T07:49:14.7043957Z",
  "expiresAtUtc": "9999-12-31T23:59:59.9999999",
  "forcePersistence": false,
  "isBodyConsumed": false,
  "label": null,
  "lockedUntilUtc": null,
  "lockToken": null,
  "messageId": "ed03a9f0-3829-43f9-9a66-c8cb218dfedf",
  "partitionKey": null,
  "properties": {
    "NServiceBus.Transport.Encoding": "application/octect-stream",
    "NServiceBus.MessageId": "286382a8-2103-4d13-8f1f-ad830080e1c9",
    "NServiceBus.MessageIntent": "Publish",
    "NServiceBus.ConversationId": "9585c069-a6af-465a-9a4e-ad830080e1c9",
    "NServiceBus.CorrelationId": "286382a8-2103-4d13-8f1f-ad830080e1c9",
    "NServiceBus.OriginatingMachine": "default000001",
    "NServiceBus.OriginatingEndpoint": "Nservicebus.SomeEndpoint",
    "$.diagnostics.originating.hostid": "9a5fd04bc8db78ec116cde0e70855410",
    "NServiceBus.ContentType": "application/json",
    "NServiceBus.EnclosedMessageTypes": "SomeFQDN, SomeAssembly, Version=1.21.812.13, Culture=neutral, PublicKeyToken=null",
    "NServiceBus.Version": "7.2.3",
    "NServiceBus.TimeSent": "2021-08-13 07:49:14:694480 Z"
  },
  "replyTo": null,
  "replyToSessionId": null,
  "scheduledEnqueueTimeUtc": "0001-01-01T00:00:00",
  "sequenceNumber": 1,
  "sessionId": null,
  "size": 1060,
  "state": 0,
  "timeToLive": "10675199.02:48:05.4775807",
  "to": null,
  "viaPartitionKey": null
}
```

I expected to be able to send this message to a queue:
- Right click on queue: "Send messages"
- Click open and select the brokered message json file
- I generate a new "messageId" and "NServiceBus.MessageId" property.
- I leave the message format to "Text" and click "Start"

This gives me the following result:
2021-08-13 11_16_13-Window

The message is successfully sent to the queue
When I look up the new generated message by messageId I see that when a handler picks up the message it is unable to extract logical messages from incoming physical message. In my case this in an NServicebus message, which would use the "NServiceBus.EnclosedMessageTypes" property for this.
When inspecting the message I see that the complete contents of the brokered message in JSON format are in the message body which seems strange to me.

My expectations are that:
- When opening the message I should only see the message body in the "message text" field
- Properties in the "properties" object should be displayed in the "Message Properties" list on the right
- All other properties on the top level should be used behind the scenes

Are my assumptions correct or am I doing something wrong?

I contacted Yves Goeleven about this, who contacted @SeanFeldman about this.
If you need more information to reproduce the issue or if I made a mistake, please let me know.

Also I noticed when I left a message property empty, like this:
2021-08-13 10_49_18-Window

I'm getting the following error:
```
<10:47:30> The following validations failed:
 -  property conversion error: Object reference not set to an instance of an object.
<10:47:30> Exception: Value cannot be null.
           Parameter name: The BrokeredMessage parameter cannot be null.. Method <SendMessages>b__1: retry 1 of 10.
<10:47:30> Exception type was: System.ArgumentNullException.
.....
<10:47:31> Exception: Value cannot be null.
           Parameter name: The BrokeredMessage parameter cannot be null.. Method <SendMessages>b__1: retry 10 of 10.
<10:47:31> Exception type was: System.ArgumentNullException.
<10:47:31> Sender[0]:
            - Exception occurred: Value cannot be null.
           Parameter name: The BrokeredMessage parameter cannot be null.
            - Message Count=[0] Messages Sent/Sec=[0,0] Total Elapsed Time (ms)=[0]
            - Average Send Time (ms)=[0] Minimum Send Time (ms)=[0] Maximum Send Time (ms)=[0] 
```
Not related to the main issue, but maybe it helps someone in the future.

### PR DESCRIPTION
**Pull request by SeanFeldman**
Fixes #586

This PR is an **attempt** to fix the export/import of JSON messages.

There's a whole slew of broken things with the current code base 😞

- Serialization
  - ❌ Incorrectly stored body - the body is stored as an object rather than raw JSON. To work properly, the body has to be saved as an escaped JSON string.
  - ❌ Incorrectly stored properties/headers - headers are stored as an object where it should be an array of key/value objects
- Deserialization
  - ❌ Incorrectly deserialized body - deserialized property is called `content` rather than `body`
  - ✖️ Incorrect merging of deserialized properties/headers and custom provide via app properties/headers - properties provided via app are lost. Don't think it matters since a restored message can be tweaked via modifying the serialized text.

To make it worse, there are multiple paths of invocation and reuse for XML & JSON.
Frankly, I don't know if it's worth spending time fixing it; fixing one thing will break something else.

I'm going to **attempt** fix JSON as this is the most common message serialization type used. No guarantees it won't break XML or other formats the application claims to support.

- [x] Fix body serialization
- [x] Fix body deserialization
- [x] Fix property serialization 
- [x] Works with a single exported message (queue)
- [x] Works with multiple exported messages (queue)
- [x] Works with DLQ-ed single message (queue)
- [x] Works with DLQ-ed multiple messages (queue)
- [x] Works with a single exported message (topic/subscription)
- [x] Works with multiple exported messages (topic/subscription)
- [x] Works with DLQ-ed single message (topic/subscription)
- [x] Works with DLQ-ed multiple messages (topic/subscription)
- [x] Investigate what "Template" stands for - _no longer relevant_
- Serialization/deserializaton from to/files other than JSON is not working --> Raised as https://github.com/paolosalvatori/ServiceBusExplorer/issues/619
- [x] Save application properties types and do not hardcode to `String`

### Preserving types

https://user-images.githubusercontent.com/1309622/158310081-586550e7-970b-4b13-b172-a92f02f5ff6e.mp4

### Single message export/import

https://user-images.githubusercontent.com/1309622/158314129-82c0d2b7-4bc3-471a-8455-5f094b4f48e3.mp4

### Multiple messages export/import

https://user-images.githubusercontent.com/1309622/158316558-23f6f0e7-d186-4a21-8918-2a4558563eed.mp4

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:x: [Build ServiceBusExplorer 902 failed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/42885893) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/78288e22a5 by @SeanFeldman)

**Comment by SeanFeldman** [comment]
:x: [Build ServiceBusExplorer 904 failed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/42886210) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/f04488ee52 by @SeanFeldman)

**Comment by SeanFeldman** [comment]
@benclerix-cegeka, if you'd like to pull down this branch and give it a try, I'd appreciate it.

Something to keep in mind - the saved JSON is no longer as readable as it was before, but it's de-serializable.
I haven't tested it on an array of messages, only a single message.

**Comment by benclerix-cegeka** [comment]
I built the sln and opened `src\ServiceBusExplorer\bin\Debug\net462\ServiceBusExplorer.exe`.

Whenever I open a queue I get the following exception:

```
<09:52:02> Exception: The type initializer for 'Azure.Core.ClientOptions' threw an exception.
<09:52:02> InnerException: Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
<09:52:22> Exception: The type initializer for 'Azure.Core.ClientOptions' threw an exception.
<09:52:22> InnerException: Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

Maybe I'm doing something wrong?

**Comment by SeanFeldman** [comment]
> I built the sln and opened `src\ServiceBusExplorer\bin\Debug\net462\ServiceBusExplorer.exe`.

What IDE did you use?

**Comment by SeanFeldman** [comment]
:x: [Build ServiceBusExplorer 906 failed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/42895860) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/481d80d043 by @SeanFeldman)

**Comment by SeanFeldman** [comment]
:x: [Build ServiceBusExplorer 908 failed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/42895911) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/5810650166 by @SeanFeldman)

**Comment by SeanFeldman** [comment]
:x: [Build ServiceBusExplorer 910 failed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/42895977) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/2df5ab12c7 by @SeanFeldman)

**Comment by SeanFeldman** [comment]
:x: [Build ServiceBusExplorer 914 failed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/42898390) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/bcb3b6397f by @SeanFeldman)

**Comment by SeanFeldman** [comment]
:x: [Build ServiceBusExplorer 916 failed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/42898553) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/9e9f67547c by @SeanFeldman)

**Comment by SeanFeldman** [comment]
@paolosalvatori @ErikMogensen, have a look at the [change in action](https://github.com/paolosalvatori/ServiceBusExplorer/pull/617#issue-1167951567). I had to raise an additional bug issue that is outside of this work scope.

Next, I need to figure out why GitVersion is failing to unblock this PR.

**Comment by SeanFeldman** [comment]
:x: [Build ServiceBusExplorer 917 failed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/42898973) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/3ce966ea64 by @SeanFeldman)

**Comment by benclerix-cegeka** [comment]
> > I built the sln and opened `src\ServiceBusExplorer\bin\Debug\net462\ServiceBusExplorer.exe`.
> 
> What IDE did you use? Try a different environment/machine. I've had no issues (used VS2019, VS2022, Rider2021)

Never mind: yesterday I tried to run the `ServiceBusExplorer.exe` directly from the bin folder which doesn't work.
When I run it from within VS2019 it does run as expected.
I tested the fix and it works perfectly.
Thanks for looking into this!

**Review by ErikMogensen — COMMENTED** [review]
Looks good to me. I know that previously Paolo wanted to have the regions.

**Comment by SeanFeldman** [comment]
Last outstanding and unrelated to the change issue is GitVersion which decided to break.

**Comment by paolosalvatori** [comment]
Hi @SeanFeldman do you need me to approve the PR or are you still working on it?

**Comment by SeanFeldman** [comment]
@paolosalvatori, first, I need to figure out why GitVersion is failing.

**Comment by SeanFeldman** [comment]
:x: [Build ServiceBusExplorer 921 failed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/43064814) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/3ce966ea64 by @SeanFeldman)

**Pull request closed without merging**
