### PR TITLE
Revert high dpi changes

### PR DESCRIPTION
**Pull request by ErikMogensen**
As mentioned in #804, there are some GUI things that don't look good after the changes for high DPI. Therefore this change reverts those changes.

Sorry @jmoralesv. I hope you will find the time to get this working for those scenarios.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
@ErikMogensen, could you please squash those two commits? A revert is better to be a single commit. Thanks.

**Comment by ErikMogensen** [comment]
> @ErikMogensen, could you please squash those two commits? A revert is better to be a single commit. Thanks.

Don't you think it is enough to do it when merging it into the main branch? The end result will be same, as far as I can tell.

**Comment by SeanFeldman** [comment]
When looking at the PRs, merged or not, they retain all the commits. When a PR is "revert", it's better to have a single commit.

**Comment by ErikMogensen** [comment]
> When looking at the PRs, merged or not, they retain all the commits. When a PR is "revert", it's better to have a single commit.

That's true. Looks like I have to abort this PR and create a new one.

**Pull request closed without merging**
