### PR TITLE
Ability to filter queue and subscription messages

### LINKED ISSUE #249: Support DateTime as filter
It would be extremely useful to support DateTime objects in the filters expression when viewing messages.  We would like to view, for instance, message with EnqueuedTimeUtc between dates A and B.

### PR DESCRIPTION
**Pull request by gitricharde**
Fixes #249.

Filter messages by enqueued date in combination with the SQL filter.
Added new dialog to capture from and to dates.
Refactored filter code in both queue and subscription forms.
Added new icon images to launch new date dialog.
Updated text displayed in the log window.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-PullRequest0338.107.build.560 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/23491567) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/5d65ba1f66 by @asosricharde)

**Comment by SeanFeldman** [comment]
Thank you @gitricharde.
Could you please attach screenshots to have a rough idea of the changes you're proposing?

**Comment by gitricharde** [comment]
Hi Sean,

Here are a few screen shots as requested...

New calendar icon next to existing text filter, present on messages and deadletters for queues and subscriptions.

image

New date range dialog

image

Logs of from date, to date, and combinations of date and text filter

image

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-PullRequest0338.111.build.564 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/23560229) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/2ac4a8e52a by @asosricharde)

**Comment by gitricharde** [comment]
@SeanFeldman That was the default behaviour when applying the existing text filter if it returned no messages. I have applied an additional commit to alter this behaviour to affect the message text and property controls whichever filter is being applied.

image

**Comment by paolosalvatori** [comment]
Great PR, thanks a lot @gitricharde!

**Pull request merged**
