### PR TITLE
Added commandline argument to alter theme to a darker theme. Use -dark…

### LINKED ISSUE #299: Dark theme?
Can you add option for Dark Theme?

### PR DESCRIPTION
**Pull request by gitricharde**
Fixes #299  

Added command-line argument to alter theme to a darker theme. Use `-dark theme true` or `/darktheme true` to indicate you want the dark theme. Omit this or set the value to false to have the default colours. All colour settings contained in the `CustomColorHelper` class.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-PullRequest0306.88.build.524 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/22577603) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/63bf50932c by @asosricharde)

**Comment by SeanFeldman** [comment]
For UI related changes, could you please provide a few snapshots?
I'm not a UI expert. Will defer to others to review in depth.
Thank you @gitricharde

**Comment by gitricharde** [comment]
image

**Comment by gitricharde** [comment]
Blurred to protect our anonymity 

image

**Comment by gitricharde** [comment]
image

**Comment by gitricharde** [comment]
image

**Comment by gitricharde** [comment]
image

**Comment by gitricharde** [comment]
Thanks @ErikMogensen, my bad :(

Working on your requests!

**Comment by gitricharde** [comment]
> The big one is regarding that any custom code in the *.designer.cs files will get lost when anything is changed using the VS GUI Designer. That means that the calls to CreateThemeColor would have to be manually replaced anytime there was such a change. Therefore it would be better to have the color set in the Paint event or some similar event.

Overriding the Paint method is proving to be problematic with existing custom control code with existing overridden properties. 
Further investigation required.

> * It would be great if the Title bar was black too
The main window is drawn by the OS and whilst can be changes, it's non-trivial.

**Comment by ErikMogensen** [comment]
@gitricharde, what do you think about putting the coloring in the Load event?

**Comment by paolosalvatori** [comment]
@gitricharde did you implement this feature in a consistent manner for all the forms & controls? Did you implement all the changes suggested by Erik? Thanks!

**Comment by gitricharde** [comment]
Not yet @paolosalvatori!

**Pull request closed without merging**
