### PR TITLE
Set C# version to 7.3

### PR DESCRIPTION
**Pull request by ErikMogensen**
Fixes the release builds part of #186.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.1.0-PullRequest0258.273.build.473 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/build/4.1.0-PullRequest0258.273.build.473) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/424c5bf0af by @ErikMogensen)

**Comment by SeanFeldman** [comment]
Yes, it should be always set.
Is it still not possible to use the new csproj with winforms? Would make csproj files so much cleaner.

**Comment by SeanFeldman** [comment]
@paolosalvatori PR pending your review

**Comment by ErikMogensen** [comment]
I built the version of SBE that was merged today with PR #261, which is built with C# 7.3, and tested it on a Windows machine running .NET 4.6.2 and there were no issues. 

I used this PowerShell expression to get .NET version:
Get-ChildItem "HKLM:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\" | Get-ItemPropertyValue -Name Release 

and used the table at https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#to-find-net-framework-versions-by-querying-the-registry-in-code-net-framework-45-and-later to interpret the output.

But this PR is obsolete now since #263 already incorporates this :)

**Comment by ErikMogensen** [comment]
Bringing up this one again since I was contacted by a friend who was unable to build SBE. It turned out to be that he needed to update his Visual Studio. Even though the readme says that you need a minimum version of VS 2017, most people don't read it. 

I believe that there are many people who try to build SBE, but give up when they get strange build errors.

**Comment by SeanFeldman** [comment]
What do you suggest?

**Comment by ErikMogensen** [comment]
I suggest we set C# version to 7.3.

**Comment by SeanFeldman** [comment]
Isn't `latest` is 7.3?

>  Projects targeting any released version will use C# 7.3 (the latest released version). This behavior means that any project targeting .NET Framework will use latest (C# 7.3).

_[source](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version)_

**Comment by ErikMogensen** [comment]
Yes, 7.3 is the latest supported version with 8 in preview. By explicitly setting C# to 7.3 then you get an error telling you that your VS to old if you try to build SBE with a an old version of VS.

**Comment by SeanFeldman** [comment]
I'm not a big fan of constraining the latest version just to generate an
eerie message for those that use an old version of VS.

Ignorance of law excuses no one.

**Comment by ErikMogensen** [comment]
It is not about constraining. It is about being clear what the constraints/law is. Otherwise how shall people know what is the expected version of C# to use? The latest may not always be the right answer.

**Comment by SeanFeldman** [comment]
I question if having 7.3 version hard-coded in the csproj would make it more clear. Regardless of what I think, if decision will be to change it and update each time latest is a different version, by all means 🙂

**Comment by ErikMogensen** [comment]
I don't mind doing creating PRs for that. I think it will be once or twice per year.

**Comment by ErikMogensen** [comment]
The hard work is getting the PRs approved ;)

**Comment by SeanFeldman** [comment]
The hardship is in the nature of async discussions.
I tend not to approve w/o having to agree on what's changed or having expectations sorted out.
Yes, I'm old 🙂

**Comment by ErikMogensen** [comment]
:)

**Pull request merged**
