### PR TITLE
release-5.0.4

### PR DESCRIPTION
**Pull request by SeanFeldman**

### CODE REVIEW

**Comment by SeanFeldman** [comment]
@paolosalvatori @ErikMogensen looks like 5.0.3 was not merged using a commit but rather squashed merged. That's likely the root on the conflicts.

**Comment by paolosalvatori** [comment]
@SeanFeldman How do you want / suggest to resolve the conflicts?

**Comment by SeanFeldman** [comment]
I'll give it a whirl this weekend.

**Comment by SeanFeldman** [comment]
[5.0.4](https://github.com/paolosalvatori/ServiceBusExplorer/releases/tag/5.0.4) is out.

**Pull request merged**
