### PR TITLE
Reformat multi-line tooltip source code for readability

### PR DESCRIPTION
**Pull request by apjanke**
The Connection String tooltip source code is hard to read, and the long line causes a "wide" horizontal scroll bar in the editor. Would you consider reformatting it over multiple lines for readability?

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-PullRequest0328.95.build.539 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/23080105) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/02bdfdab24 by @apjanke-ccs)

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-PullRequest0328.101.build.544 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/23082036) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/aad46d145c by @ErikMogensen)

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-PullRequest0328.102.build.545 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/23082121) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/92f0a0105f by @ErikMogensen)

**Comment by apjanke** [comment]
> I made a change in the text.

LGTM.

**Comment by paolosalvatori** [comment]
Thanks @apjanke

**Pull request merged**
