### PR TITLE
Documentation Simplification

### LINKED ISSUE #127: Update README.MD with meta information about the repo
Document things such as
- VS and C# version requirement
  - Fortify
  - Support branches policy
- Versioning and releases
  - Include future plans
- _Consider_ moving documentation into appropriate (linked) location similar to how other projects are doing it ([GitVersion](https://gitversion.readthedocs.io/en/latest/), [BenchmarkDotNet](http://benchmarkdotnet.org/Guides/GettingStarted.htm), [AutoMapper](https://github.com/AutoMapper/AutoMapper/wiki/Getting-started), etc)

### PR DESCRIPTION
**Pull request by tomkerkhove**
Fixes #127 
Incorporated most feedback from #132.

I'll leave the other comments up to you to decide.
Basically all the legacy is out and I think new docs should be provided, if applicable.

I'm not sure if the `NEWFEATURES.md` is even still relevant or if it should be removed as well since we have GH issues now.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.0.98-PullRequest0133.27.build.261 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/build/4.0.98-PullRequest0133.27.build.261) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/f60d6d1e7d by @tomkerkhove)

**Comment by paolosalvatori** [comment]
Good work guys, Please remove Cerebrata from the list of alternative tools, and restore the link to ServiceBus360. For the management portal, please add a link to https://ms.portal.azure.com. :) Thanks!!! :)

**Comment by paolosalvatori** [comment]
We need to change the list of links at the end of the History of Azure Service Bus. I suggest we take the definition of Azure Service Bus from the documentation and replace the title from History of... to simply Azure Service Bus.

**Comment by SeanFeldman** [comment]
> Please remove Cerebrata from the list of alternative tools

Any specific reason?

**Comment by paolosalvatori** [comment]
Contact me offline :)

**Comment by SeanFeldman** [comment]
Ok.
I'm flying to Italy 😃

**Comment by tomkerkhove** [comment]
@paolosalvatori To what do you want to change the links?

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.0.98-PullRequest0133.28.build.262 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/build/4.0.98-PullRequest0133.28.build.262) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/eb04258416 by @tomkerkhove)

**Comment by tomkerkhove** [comment]
Changed the Azure Service Bus section, let me know what you think. I've removed the links at the bottom now that it points to the official docs.

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.0.98-PullRequest0133.29.build.263 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/build/4.0.98-PullRequest0133.29.build.263) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/bc64f891dd by @tomkerkhove)

**Comment by paolosalvatori** [comment]
Almost there :) @tomkerkhove can you please:
 - Add a paragraph called Service Bus Explorer before Installation and use the following wording
"The Service Bus Explorer allows users to connect to a Service Bus namespace and administer messaging entities in an easy manner. The tool provides advanced features like import/export functionality or the ability to test topic, queues, subscriptions, relay services, notification hubs and events hubs."
 - Immediately below, please reuse the picture to the tool that you removed.
That's it :)

**Comment by SeanFeldman** [comment]
Please wait with merging until #134 is completed.

**Comment by SeanFeldman** [comment]
#134 is done, no longer blocking.

**Comment by tomkerkhove** [comment]
I'll change the rest this evening!

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.0.99-PullRequest0133.31.build.265 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/build/4.0.99-PullRequest0133.31.build.265) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/482cd09c54 by @tomkerkhove)

**Comment by paolosalvatori** [comment]
Almost there :) Two more changes guys:
Replace the following section

**Important Note**

The zip file contains:
•The source code for the Service Bus Explorer 3.0.4. This version of the tool uses the Microsoft.ServiceBus.dll 3.0.4 that is compatible with the current version of the Azure Service Bus, but not with the Service Bus 1.1, that is, the current version of the on-premises version of the Service Bus.
•The Service Bus Explorer 2.1.3.0. This version can be used with the Service Bus 1.1. The Service Bus Explorer 2.1 uses the Microsoft.ServiceBus.dll client library which is compatible with the Service Bus for Windows Server 1.1 RTM version. You can download the source code of the Service Bus Explorer v2.X here.

with

**Service Bus Explorer for Windows Server**
The Service Bus Explorer 2.1.3.0 can be used with the Service Bus 1.1. The Service Bus Explorer 2.1 uses the Microsoft.ServiceBus.dll client library which is compatible with the Service Bus for Windows Server 1.1 RTM version. You can download the source code of the Service Bus Explorer v2.X here.

Can you please create a file containing the update log? I mean the section that in the current version of the readme file starts with the title Service Bus Explorer. When you created that file, please add a link to the readme file under a section called Tool Documentation.

Tool Documentation
Here you can find the tool documentation and a log of the features implemented over time.

**Comment by tomkerkhove** [comment]
@paolosalvatori Sure I'll add the server stuff later today.

About the release notes, I started converting that but it was more than 2 years old, is it worth keeping that around? If so, I think it's not worth converting it since it will not be updated anymore.
Thoughts on this?

**Comment by SeanFeldman** [comment]
Release notes should be under releases in GH.
Listing then seriously now as good as listing your daily childhood events 20 years later 🙂

**Comment by paolosalvatori** [comment]
Well, regarding release notes, I'd remove the parts where I mention fixes and keep those parts where I explain features. I'm aware that fixing this stuff needs time. We can just add a section at the end that says:

Release Notes
You can find release notes here.

Then, only if you have spare time and not necessarily now, you can fix the document and just remove dates and fixes and keep only those parts that explain features.

**Comment by tomkerkhove** [comment]
I added the section as-is in a dedicated file. I left the release notes out since that is tied per release, is that correct @SeanFeldman?

**Comment by paolosalvatori** [comment]
Just call this section Documentation for now... History of Service Bus Explorer is too verbose :) Then we can ship it in my opinion. Last change, promised :) Also please change the wording of the Service Bus Explorer for Windows Server section to:

The Service Bus Explorer 2.1.3 can be used with the Service Bus for Windows Server 1.1. The Service Bus Explorer 2.1.3 uses a version of the Microsoft.ServiceBus.dll client library which is compatible with the Service Bus for Windows Server 1.1 RTM version. You can download the source code of the Service Bus Explorer 2.1.3 here.

**Comment by SeanFeldman** [comment]
> History of Service Bus Explorer is too verbose

Looks like @paolosalvatori wants to keep that for his memoir 🙂

**Comment by tomkerkhove** [comment]
@paolosalvatori I updated it but I think we should change the mentioned version to 2.1.0 since that is the [released legacy version](https://github.com/paolosalvatori/ServiceBusExplorer/releases/tag/2.1.0). What do you think?

**Comment by SeanFeldman** [comment]
@tomkerkhove I just made the same comment. Criminal minds think alike.

**Comment by tomkerkhove** [comment]
Took the liberty to align it with the released version, can still change it back to v2.1.3 if you want @paolosalvatori

**Comment by paolosalvatori** [comment]
I reviewed the latest version of the readme file and... let's ship it :)

**Comment by tomkerkhove** [comment]
Thanks!

**Comment by SeanFeldman** [comment]
:tada:

**Pull request merged**
