### PR TITLE
Release 4.0.110

### PR DESCRIPTION
**Pull request by SeanFeldman**
- Bug: SBE doesn't show Topics and Queues whilst Azure portal shows them (#205)
- Bub: Explorer attempts to connect to a ASB that cannot be resolved to a host name. (#209)
- Enhancement: Do not alter dates when indenting JSON (#215)
- Enhancement: Remove default max length of 32767 for most text boxes (#219)
- Enhancement: Remove support for Service Bus metrics (#212)
- Enhancement: Remove message from DLQ error Exception (#227)

### CODE REVIEW

**Comment by SeanFeldman** [comment]
Next release @paolosalvatori

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.1.0-PullRequest0223.225.build.408 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/build/4.1.0-PullRequest0223.225.build.408) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/fb5eefdbe3 by @paolosalvatori)

**Comment by tomkerkhove** [comment]
This is going to release the metrics changes (#212) that are not finished yet. Should we wait on this?
If so, we first need to have some body take that up.

**Comment by paolosalvatori** [comment]
@SeanFeldman, I agree with @tomkerkhove  I'm not going to merge changes as they are incomplete. I also realized that there are other regression bugs that need to be fixed. I'll open an issue when I have some time.

**Comment by SeanFeldman** [comment]
Folks, extract to another branch, revert those changes, and move on.

We shouldn't be blocking just because of the accidental merge.

>

**Comment by paolosalvatori** [comment]
Hi @SeanFeldman I have no time for that, sorry about that. If no one has time to complete changes or revert the develop branch to the previous state, we'll proceed and merge changes in maximum one week from today

**Comment by ErikMogensen** [comment]
I'll start working to complete #212.

**Comment by ErikMogensen** [comment]
@SeanFeldman , I found an issue with the scrollbars, at least on the two computers I tested the latest commit in develop on. I created #224 for this. I believe I have fixed it. I think the fix must be part of this release. May I just create a PR as usual or do I need to anything special?

**Comment by SeanFeldman** [comment]
PR against develop branch?
Absolutely. We'll rebase this PR's branch on top of the new develop when
it's ready.

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.1.0-PullRequest0223.244.build.424 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/build/4.1.0-PullRequest0223.244.build.424) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/fa9285ce4d by @paolosalvatori)

**Comment by SeanFeldman** [comment]
@paolosalvatori 4.0.110 is ready. Once you merge it, we'll have a release.

**Pull request merged**
