### PR TITLE
[WIP] Convert a zip into support branch

### LINKED ISSUE #58: Link doesn't work
http://1drv.ms/1nEl7ps

### PR DESCRIPTION
**Pull request by SeanFeldman**
fixes #58 
plus a few minor cleanups

**DO NOT MERGE**
1. Create a `support-2.1` branch
2. re-target this PR against `support-2.1` branch

### CODE REVIEW

**Comment by SeanFeldman** [comment]
@paolosalvatori ping

**Comment by paolosalvatori** [comment]
Ping me on skype :)

**Comment by SeanFeldman** [comment]
blocked by @paolosalvatori 😛

**Comment by paolosalvatori** [comment]
What do you need me to do @SeanFeldman? :) I promoted you collaborator on the repository.  Let me know if you can proceed now!

**Pull request closed without merging**
